# Dependencies
markdown:         kramdown
#highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            Paulo Morales Castillo
tagline:          Analytics/Data Engineer
#description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://paulomoralescastillo.com
baseurl:          /

author:
  name:           Paulo Morales Castillo
  url:            https://paulomoralescastillo.com

#paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           #https://

# pluggins

#plugins:        [jekyll-paginate]

# Social media usernames
github_username:    moralescastillo
linkedin_username:  moralescas
strava_username:    paulo_mc

exclude:
  - .jekyll-cache

google_analytics: G-79GPSHLYJ6