#-------------------------------
# Site Settings
title: Paulo Morales Castillo
#logo: /images/SYMBOL-WHITE-TRANSPARENT.png # You can add own logo. For example "/images/logo.png".
description: Multipurpose Jekyll Blog Theme


#-------------------------------
# Author Global Settings
author:
  author__name: Paulo Morales Castillo
  author__bio: >
    I am a freelance analytics/data engineer based in Berlin, Germany, 
    who is constantly learning and experimenting with new technologies. 
    With a background in data analytics since 2014, I have gained 
    expertise in various areas such as data science, data engineering, 
    web analytics, and marketing analytics. My core skills include 
    descriptive, exploratory, and predictive data analysis, 
    data warehouse setup and maintenance, data orchestration and 
    transformation, and dashboard creation and automation. I also run 
    long distances from time to time. 
  author__avatar: /images/0_author_admin.jpg


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    #- title: 'Pages'
    #  submenu:
    #  - url: '/authors/'
    #    title: 'Authors'
    #  - url: '/elements/'
    #    title: 'Elements'
    #- title: 'Tags'
    #  url: '/tags/'
    - title: 'Contact'
      url: '/contact/'


#-------------------------------
# Hero Settings
hero:
  hero__title: >
    Hi there! My name is Paulo and I am a freelance data all-arounder 
    based in Berlin, Germany. Welcome to my blog.


#-------------------------------
# Blog Settings
blog:
  blog__title: Blog
  blog__description: 


#-------------------------------
# Recommended Tag Settings
tag:
  enable: false
  tag__title: Recommended
  tag__name: Motivation


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: false
  mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp__title: Get interesting news
  mailchimp__description: Subscribe to our newsletter and we’ll send you the emails of latest posts.
  mailchimp__input__text: Your Email Address...
  mailchimp__button__text: Subscribe
  mailchimp__background__image: "/images/110.jpg"


#-------------------------------
# Footer Settings

# Footer Navigation
footer__menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Contact'
      url: '/contact/'
    #- title: 'Authors'
    #  url: '/authors/'
    #- title: 'Elements'
    #  url: '/elements/'


# Social Links
social:
- {icon: "ion-logo-github", color: "#000000", name: Github, link: "https://github.com/moralescastillo"}
- {icon: "ion-logo-linkedin", color: "#0A66C2", name: LinkedIn, link: "https://www.linkedin.com/in/moralescas/"}
- {icon: "ion-logo-twitter", color: "#55acee", name: Twitter, link: "https://twitter.com/PauloMoralesCas"}
#- {icon: "ion-logo-facebook", color: "#3b5999", name: Facebook, link: "https://facebook.com"}
#- {icon: "ion-logo-pinterest", color: "#bd081c", name: Pinterest, link: "https://pinterest.com"}
#- {icon: "ion-logo-dribbble", color: "#ea4c89", name: Dribbble, link: "https://dribbble.com"}
#- {icon: "ion-logo-instagram", color: "#e4405f", name: Instagram, link: "https://instagram.com"}

# Example of adding a new link to the footer - {icon: "ion-logo-youtube", color: "#ff0000", name: Youtube, link: "https://youtube.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: xyyqykpp # Add your email for contant form

# NOTE
# Dann theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: false
  disqus__identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id